### ISSUE TITLE
Divergences from ffmpeg on LC-AAC files from 0.6 to 2.0

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#100]
[These files](https://mega.nz/file/E11A3T4R#u4DBzFZ9YgJ4Z4BOJhF8MzpKiOzq8E8LTwstUU17Vio) produce divergences from ffmpeg ranging from 0.6 to 2.0; at the same time the files are listenable, so I assume some sort of misalignment is happening. I could not find a single file that would not diverge significantly.

I've verified that all these files are indeed LC-AAC and not a different AAC profile using `mediainfo`.

Tested on commit ee27dfdd2a60384627108132fcbe1742e2c181cb, the latest as of this writing.

**Comment by Shnatsel** [comment]
Some of these drop down all the way to 0.000002 with `--no-gapless`

**Comment by pdeljanov** [comment]
Testing AAC isn't going to be worthwhile yet. I know of many inaudible glitches in the decoder, and the ISO/MP4 container doesn't support gapless playback yet.

You may get a bit further with `--no-gapless`, but failures are definitely expected. This will have to be a 0.5.1 task though since I estimate a couple months of effort here.

**Comment by Shnatsel** [comment]
Yeah, I was about to say that holding up 0.5 is probably not worth it. I want to get the memory-safe MP3 decoding into the hands of users ASAP.

**Comment by Shnatsel** [comment]
Regarding the v0.5.1 milestone: with LC-AAC being more than listenable even on files that fail the check, and the format being somewhat niche, I'd much rather see work on e.g. Opus decoder than further polish on LC-AAC.

**Comment by pdeljanov** [comment]
I'm going to have to disagree with you on this. AAC-LC is one of the most popular codecs out there, particularly in the Apple ecosystem. All music purchased or encoded on iTunes is AAC. AAC is also the typical audio codec used in MP4 and many MKV files. YouTube also serves videos with AAC audio to the app. Opus on the other hand seems to only have been embraced by voice chat apps and YouTube web. For this reason, fixing AAC is a higher-priority.

My vision for the 0.5.x series of releases is to fix the outstanding quality issues (AAC, maybe fuzzing) with the existing decoders & demuxers, and then to fill in the easy low-hanging fruit in the roadmap (MP1, MP2, probably ADPCM as requested, maybe WavPack). Once those non-semver breaking issues are resolved, I will make a 0.6 release to resolve the API pain points. After all that, I'm hoping the maintenance burden of Symphonia will become much less and that I can spend that time on Opus instead.

**Comment by pdeljanov** [comment]
The majority of these files are now passing!

The few failing files exhibit errors in both Symphonia and `ffmpeg` and are limited to a few packets. However, `symphonia-check` aborts on the first invalid packet giving a worse impression.
