### ISSUE TITLE
MP3: Mismatches on the "AMV collection v6.0" corpus

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#105]
There are some mismatches with FFmpeg when decoding MP3s from the [AMV Collection v6.0](https://nyaa.si/view/1356775) corpus, as suggested in the comments on the Symphonia v0.5 announcement on Reddit. This should give us some MP3s from the early 2000s that were not represented in the corpora that I tested previously.

The corpus contains video files, but I have extracted the audio part with the following command, and fed the result to Symphonia:
```
fd -tf | nice ionice parallel --bar "ffmpeg -i {} -vn -acodec copy {}.mp3 2> /dev/null"
```

The mismatching MP3 files can be obtained [here](https://mega.nz/file/9wsEkDBT#Bi2NJiwGleG3i1V7sZ5eJCTUsyUUan6BA__HEzDo_QQ) without having to download the entire corpus and re-run the extraction.

I have not done much pre-filtering, so a good chunk of that is probably due to already-known issues with ffmpeg.

There is also some AAC in there, but I've ignored it for now.

**Comment by pdeljanov** [comment]
I gave these a quick run-through, and it appears that the overwhelming majority of the issues are the same as last time.

I'll have to take a closer look at the few less obvious cases, but I expect those to be okay as well.

Thanks for testing these out, it's a very unique way to get more test-cases.

**Comment by pdeljanov** [comment]
The remainder of these seem alright!
