### ISSUE TITLE
symphonia-format-isomp4: isomp4: illegal track type in hdlr

### ISSUE THREAD

**Issue by alexferro** [pdeljanov/Symphonia#106]
I have several m4a files which hdlr.rs dies internally on line 56, and it propagated all the way out, with "isomp4: illegal track type". After some debugging, it appears it's getting a type of 'odsm' there, which is doesn't know about, and failing the entire operation. I first noticed while using rodio, but I can reproduce the issue with symphonia-play as well. "ERROR symphonia_play > file not supported. reason? malformed stream: isomp4: illegal track type".

These files all play properly in iTunes/VLC/ffmpeg, so I don't think it's actually invalid files. I also see hdlr:sdsm and other unknown hdlr values later in the file.
From a quick glance at the code, but I'm no expert, it looks like some of this might be best to just skip hdlr atoms that are unknown, rather than die?

I've attached a very invalid, but enough to demonstrate the error, file that was truncated from my original. This was an m4a, but github made me rename it to mp4 first.

https://user-images.githubusercontent.com/1122990/152716368-15e68b83-9243-4b99-8fe8-7d21cf1832dc.mp4

Edit: The attachment is all kinds of broken as github tries to display it, but I've verified that if downloaded it's my same file.

**Comment by pdeljanov** [comment]
Hi @alexferro,

Thanks for the good bug report. Yeah, failing on this is totally unreasonable. I pushed a change that should make the demuxer more lenient if it encounters a track with an unknown handler type.

This fixes the error you've reported, but since the file is truncated I couldn't test if the audio will play or get a track listing. Please let know if it works. Thanks!

**Comment by alexferro** [comment]
Oh wow. Thanks for the crazy fast turn around. I just tested with my original file and it plays back properly now. 

Thanks again.

**Comment by pdeljanov** [comment]
No problem, glad it's fixed now!
