### ISSUE TITLE
unsupported format: Unsupported("core (probe): no suitable format reader found") for an mp3 file

### ISSUE THREAD

**Issue by happysalada** [pdeljanov/Symphonia#113]
Hi, thank you for the libary.!
I followed the get started example to the letter, but I'm getting this panic on the proble.
Perhaps I'm missing something, but I double checked everything and I can't find it.
I've tried with different mp3 file, but I've commited one on the repo that can be tested
https://github.com/happysalada/audiowave_test

I've only added `symphonia` as a dependency, do I need to add other dependencies as well for this to work ?
I couldn't find the cargo.toml file for the examples, so I wasn't sure. Appart from that I don't think I'm doing anything different than the get started. If you have any idea, I'm happy to try anything of course.

**Comment by pdeljanov** [comment]
You'll need to enable the `mp3` feature to get MP3 support!

**Comment by happysalada** [comment]
I should have looked harder. Of course, it worked.
Thanks again for the heads up!
