### ISSUE TITLE
Could use encoding rather than encoding_rs to make binary size smaller?

### ISSUE THREAD

**Issue by zhouhang95** [pdeljanov/Symphonia#114]
Seems encoding_rs use all codings, but in fact we just us shift-jis and utf-16be?
In encoding crate, just import what you need into binary.

**Comment by zhouhang95** [comment]
or add a option switch between they?

**Comment by zhouhang95** [comment]
or make enconding_rs is a feature, if dev don't care this filed?

**Comment by pdeljanov** [comment]
Hi @zhouhang95,

I used `cargo bloat` to see how much space `encoding_rs` is using in a release build and it seems very minimal. It's likely less if the binary is stripped. It's probably not worthwhile changing at this time.

```
cargo bloat --release --filter encoding_rs
    Finished release [optimized] target(s) in 0.03s
    Analyzing target/release/symphonia-play

File .text    Size       Crate Name
0.1%  0.3%  5.0KiB encoding_rs encoding_rs::gb18030::Gb18030Decoder::decode_to_utf8_raw
0.1%  0.2%  4.9KiB encoding_rs encoding_rs::euc_jp::EucJpDecoder::decode_to_utf8_raw
0.1%  0.2%  4.0KiB encoding_rs encoding_rs::shift_jis::ShiftJisDecoder::decode_to_utf8_raw
0.0%  0.2%  3.4KiB encoding_rs encoding_rs::euc_kr::EucKrDecoder::decode_to_utf8_raw
0.0%  0.1%  2.8KiB encoding_rs encoding_rs::utf_16::Utf16Decoder::decode_to_utf8_raw
0.0%  0.1%  2.2KiB encoding_rs encoding_rs::big5::Big5Decoder::decode_to_utf8_raw
0.0%  0.1%  2.0KiB encoding_rs encoding_rs::iso_2022_jp::Iso2022JpDecoder::decode_to_utf8_raw
0.0%  0.1%  1.9KiB encoding_rs encoding_rs::Encoding::decode_without_bom_handling
0.0%  0.1%  1.3KiB encoding_rs encoding_rs::single_byte::SingleByteDecoder::decode_to_utf8_raw
0.0%  0.1%  1.2KiB encoding_rs encoding_rs::Decoder::decode_to_utf8_without_replacement
0.0%  0.1%  1.1KiB encoding_rs encoding_rs::utf_8::Utf8Decoder::decode_to_utf8_raw
0.0%  0.0%    961B encoding_rs encoding_rs::utf_8::utf8_valid_up_to
0.0%  0.0%    570B encoding_rs encoding_rs::variant::VariantDecoder::max_utf8_buffer_length_without_replacement
0.0%  0.0%    488B encoding_rs encoding_rs::Decoder::decode_to_utf8_after_two_potential_bom_bytes
0.0%  0.0%    477B encoding_rs encoding_rs::variant::VariantDecoder::max_utf8_buffer_length
0.0%  0.0%    388B encoding_rs encoding_rs::Decoder::max_utf8_buffer_length
0.0%  0.0%    382B encoding_rs encoding_rs::variant::VariantDecoder::decode_to_utf8_raw
0.0%  0.0%    381B encoding_rs encoding_rs::Decoder::decode_to_utf8_after_one_potential_bom_byte
0.0%  0.0%    358B encoding_rs encoding_rs::Decoder::max_utf8_buffer_length_without_replacement
0.0%  0.0%    312B encoding_rs encoding_rs::Decoder::decode_to_utf8
0.0%  0.0%    932B             And 5 smaller methods. Use -n N to show more.
0.5%  1.8% 35.0KiB             filtered data size, the file size is 7.2MiB
```

**Comment by zhouhang95** [comment]
Hello, I use crate rodio, when i use Symphonia as format decoding backend, it make bin size more 800kb than orther format decoding, why this crate cost a lot of bin size?

**Comment by zhouhang95** [comment]
the decoding work way is that make one dict, such as shift_jis to utf8, then make a function to process,
generanlly one dict is 50kb in cjk area,(gb18030, euc_jp, shift_jis, euc_kr, big5, iso_2022_jp)

**Comment by pdeljanov** [comment]
> Hello, I use crate rodio, when i use Symphonia as format decoding backend, it make bin size more 800kb than orther format decoding, why this crate cost a lot of bin size?

Symphonia supports many different formats and codecs and can replace all the other decoders on Rodio. Did you try setting `default-features = false` and then enabling the Symphonia decoders only?

> the decoding work way is that make one dict, such as shift_jis to utf8, then make a function to translate and do some corner case work, generanlly one dict is 50kb in cjk area,(gb18030, euc_jp, shift_jis, euc_kr, big5, iso_2022_jp)

I see what you mean. Unfortunately, Shift JIS is required for MP4/M4A support, so it's not possible to remove support for it entirely.

If there are smaller crates that can decode UCS2/UTF-16 and Shift JIS then I'd be happy to consider them. 

I looked at the `encoding` crate and it seems abandoned (no updates in over 5 years). I'd prefer not to switch to an unmaintained crate.

**Comment by zhouhang95** [comment]
Ok.
