### ISSUE TITLE
Support `m3u`/`m3u8` format

### ISSUE THREAD

**Issue by virtualritz** [pdeljanov/Symphonia#123]
See [`Wikipedia on M3U`](https://en.wikipedia.org/wiki/M3U). 

The [`hls_m3u8` crate](https://crates.io/crates/hls_m3u8) contains a parser for this format and looks maintained.

**Comment by pdeljanov** [comment]
Hi @virtualritz,

I think this is out-of-scope for Symphonia. Playlists are an application-level feature, while Symphonia takes responsibility for demuxing and decoding individual media files.

**Comment by virtualritz** [comment]
Fair enough. So you would also not accept a PR for this, right?

**Comment by pdeljanov** [comment]
Thanks for your understanding, but I don't think so. It wouldn't fit into any of the existing crates.

Just to provide a little bit more of my reasoning here: Symphonia's demuxers don't really understand where the media data is coming from. The general idea is that a demuxer reads from a `MediaSourceStream` which itself reads from an object implementing the `MediaSource` trait. `MediaSource` is implemented for `std::fs::File` and `std::io::Cursor` for convenience, but aside from those two, it's up-to the end-user to implement `MediaSource`.

A `MediaSource` can only ever be a single piece of media (you can't string together multiple files), so the concept of a playlist is too high-level for Symphonia to deal with.

To play a playlist with Symphonia an application would need to parse the playlist, then for each item in the playlist: create a `MediaSource` and `MediaSourceStream`, decode the stream and play it, and when finished playing, move on to the next item until the playlist is complete.

This is "player" functionality and we don't have anything like that in Symphonia at the moment. This could be a future crate item, but it's quite a large task!

**Comment by torokati44** [comment]
(Just a technical note for the future @pdeljanov: perhaps this issue should have been closed as "not planned", now that GitHub added this feature just a few days ago.)
