### ISSUE TITLE
`clap` compatibility

### ISSUE THREAD

**Issue by torokati44** [pdeljanov/Symphonia#125]
I got a compilation error when updating my old git clone to current `master`:
```
error[E0433]: failed to resolve: could not find `Command` in `clap`
  --> symphonia-play/src/main.rs:36:25
   |
36 |     let matches = clap::Command::new("Symphonia Play")
   |                         ^^^^^^^ not found in `clap`
   |
help: consider importing this struct
   |
15 | use std::process::Command;
   |

For more information about this error, try `rustc --explain E0433`.
error: could not compile `symphonia-play` due to previous error

```
It was probably introduced by: https://github.com/pdeljanov/Symphonia/commit/559f4dab81488d703d3690c30dabac886e269887
I think `clap::Command` got added only in 3.1.0: https://github.com/clap-rs/clap/blob/v3.1.17/CHANGELOG.md#310---2022-02-16=
Running `cargo generate-lockfile` fixed it.
I think, either the dependency in `Cargo.toml` should be bumped to `3.1.0`, or the `Cargo.lock` files should be checked in to the repo, and letting Dependabot take care of updating it regularly.

**Comment by pdeljanov** [comment]
Thanks, I fixed this!
