### ISSUE TITLE
Next FLAC packet after seek has wrong timestamp

### ISSUE THREAD

**Issue by dbeckwith** [pdeljanov/Symphonia#133]
I'm seeing some strange behavior around seeking a format reader. Here's a rough outline of my code:

* seek the format reader using `SeekMode::Accurate` and `SeekTo::Time`
* reset the decoder
* get the next packet from the format reader
* calculate the timestamp of the packet using the decoder's codec parameters to get a `std::time::Duration` and report it to the client as the current position of the stream

What I'm seeing is that the timestamp of the packet right after seeking is different from what I would expect. Here is what I saw in one test I did:

* seek to 58.877s
* observe logs `symphonia_bundle_flac::demuxer: seeking to frame_ts=2596475` and `symphonia_bundle_flac::demuxer: seeked to packet_ts=2592768 (delta=-3707)`
* get next packet
* calculated packet timestamp is 58.793s
* seek to 87.112s
* observe logs `symphonia_bundle_flac::demuxer: seeking to frame_ts=3841639` and `seeked to packet_ts=3837952 (delta=-3687)` (this seems correct)
* get next packet
* calculated packet timestamp is 58.886s, which is definitely not correct, although it is different from the previous packet

It's hard to tell if just the timestamp is wrong or if the actual packet contents are wrong since it's just a single packet. If I let the stream continue after this, I think the next packet is correct, but I also see the warning log `symphonia_bundle_flac::parser: rebuild failure; frame exceeds stream's frame length limit (12716 > 12249)`.

This was with a FLAC decoder. I tried a similar test with MP3 and couldn't reproduce it.

Any ideas on why this might be happening? Could it just be a bug with the FLAC decoder where after a seek, the next packet you get is from before the seek?

**Comment by pdeljanov** [comment]
Hi @dbeckwith,

This was definitely a regression. After a seek, the FLAC demuxer wasn't resetting its internal queue of partially buffered FLAC frames.

Please give the latest revision a try.

**Comment by dbeckwith** [comment]
050c892 works perfectly for me, thanks!
