### ISSUE TITLE
When will the new version be released, I am looking forward to wasm api 🤣

### ISSUE THREAD

**Issue by jeromeleong** [pdeljanov/Symphonia#136]

**Comment by torokati44** [comment]
(And I am looking forward to https://github.com/pdeljanov/Symphonia/issues/126! 😶)

**Comment by pdeljanov** [comment]
I don't think there's gonna be a WASM API for a while, but you can use Symphonia in WASM targets as-is. The Ruffle folks are doing just that.

I've been extremely busy with work for the past few months so I haven't spent much time with Symphonia. I'll aim to cut a bug fix release in the next 2~3 weeks after I have some time to properly test. Thanks for the patience.

**Comment by pdeljanov** [comment]
Released [v0.5.1](https://github.com/pdeljanov/Symphonia/releases/tag/v0.5.1)!
