### ISSUE TITLE
Implement SeekMode::Coarse for Mp3Reader to skip parsing while seeking

### ISSUE THREAD

**Issue by Azorlogh** [pdeljanov/Symphonia#139]
I'd like to have the choice to seek to a timestamp directly from the `MediaSource`, rather than the demuxer parsing all intermediary frames. In particular, this would avoid unnecessary http requests when streaming HLS content.
Ideally, it would determine an approximate byte index for the desired timestamp, using the bitrate (so it would only work for constant bitrates)

~~Note:~~
There is also another issue for streaming content in a non blocking way:
The way I'm doing it in my project is that I return an `io::ErrorKind::WouldBlock` from the read call. I intercept that error out of `FormatReader::next_call` when streaming audio, and when it happens I put my reader into a paused state, and stop calling next_frame until a delay has passed. But if `FormatReader::seek` also tries to advance the reader for frame alignment purposes, it won't succeed.
Maybe my strategy is wrong, but in my case it would be preferable to defer alignment to the next call to `next_frame` instead of `seek`
EDIT about that note: See comment below, the solution is just to prefetch the data and defer the seek call (once SeekMode::Coarse is implemented)!

**Comment by pdeljanov** [comment]
Hi @Azorlogh,

In regards to the first part, that's a good idea. Unfortunately, for MP3 the only way to do an accurate seek is by scanning the file/stream. A fast seek could be implemented in the manner you suggest. The `SeekMode` argument passed to `FormatReader::seek` is intended for this purpose. It's just that right now we only have implemented accurate seeks!

For the second part, are you trying to implement a kind of async IO? I don't think that'll work as expected. Symphonia will probably be confused by the data from the now half-read frame.. atleast some readers..

I think if you want to use Symphonia with async IO the most straightforward way would be to implement a `MediaSource` that has an internal buffer that you can fill on the async IO event loop side, and have Symphonia read in a blocking manner on the other side on its own thread.

**Comment by Azorlogh** [comment]
Makes sense!
About the second part, indeed currently I have a buffer that gets filled with 10 seconds of data in advance and which I implemented a MediaSource for. The issue is when I seek very far into the stream, I would need to load all the data in the middle.
But somehow I didn't think of simply waiting for the buffer's data to load at the new location before seeking which definitely sounds like the correct solution :sweat_smile:
In the meantime I was simply restarting the symphonia stream but I'll keep that in mind next time I go to improve that part of my code.
Btw thanks for this awesome library, it saved me so many headaches about dealing with multimedia formats directly :slightly_smiling_face:

**Comment by pdeljanov** [comment]
Coarse seeking for MP3 is now implemented. Hope it works well for you!

**Comment by Azorlogh** [comment]
Awesome!! Thanks :heart:
