### ISSUE TITLE
how to only decode mkv to mp3?

### ISSUE THREAD

**Issue by kaneruan** [pdeljanov/Symphonia#150]
Thank your job, Symphonia is excellent crate.
I am new to using Symphonia.

how to only decode mkv to mp3?

link: https://ysd2bssdlbig.kugou.com/202208011412/5906ca1be05d5113b127e844501eed98/6ab8dc838e05593106505ad1e20747f2

above link is mkv included two track.

I want to build [Symphonia](https://github.com/pdeljanov/Symphonia) to wasm, and then decode mkv to two track mp3 in browser, and then use [decodeAudioData](https://developer.mozilla.org/en-US/docs/Web/API/BaseAudioContext/decodeAudioData) to decode them(tow track mp3) to [AudioBuffer](https://developer.mozilla.org/en-US/docs/Web/API/AudioBuffer).

**Comment by pdeljanov** [comment]
Hi @kaneruan,

If I understand the question, you want to get the MP3 data from the MKV file, but *not* decode it with Symphonia. Instead, you want to the decode the MP3 data with the web API?

To do that you can follow the [Getting Started](https://github.com/pdeljanov/Symphonia/blob/master/GETTING_STARTED.md) guide, but skip the parts about decoders and decoding.

Once you get a `Packet` from `next_packet`, you can get the raw MP3 data from the `data` field and pass that to the web API.
