### ISSUE TITLE
Audio glitch with isomp4/ACC sample provided

### ISSUE THREAD

**Issue by ccgauche** [pdeljanov/Symphonia#151]
SAMPLE:

https://user-images.githubusercontent.com/16625987/183244743-c796c2b1-c45d-4d36-b889-0f026c37a162.mp4

The voice seems clear but the instrumental part especially at the beginning is glitchy.

**Comment by pdeljanov** [comment]
Hi @ccgauche,

Thanks for the bug report.

The AAC decoder has some known glitches, but this is definitely the worst I've heard. I'm aiming to have the glitches fixed for v0.5.2 or v0.5.3. This file should definitely help in tracking down the issues.

**Comment by pdeljanov** [comment]
This is fixed now. Thanks again for the sample!
