### ISSUE TITLE
How to load Metadate from the Files?

### ISSUE THREAD

**Issue by cherob** [pdeljanov/Symphonia#152]
I want to load ID3 other Audio Metadata from a File.

title, artists, bpm, etc...

**Comment by cherob** [comment]
```rust
thread` 'main' panicked at 'end of stream', src\test_read.rs:62:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by SuisChan** [comment]
Repository has [symphonia-play](https://github.com/pdeljanov/Symphonia/tree/master/symphonia-play), there is an example of what you are looking for [link](https://github.com/pdeljanov/Symphonia/blob/master/symphonia-play/src/main.rs#L140)

**Comment by cherob** [comment]
I had tryed to get into the Code but in my Tests it wont work. If someone could pase a Example Code for following case:

1. Load a Audio File by defined Path variable
2. Print out the Title in Console
3. Set Album of Audio File to the String "Test"

If anyone could wrap smt around this, you could also add it to the Documentation^^.

**Comment by cherob** [comment]
![grafik](https://user-images.githubusercontent.com/15168847/184179099-abf6a28e-4cd0-4c69-a5b3-3f93dd8d2d5a.png)
I want to edit these Metadata + if possible ID3 and EXIFF later on

**Comment by cherob** [comment]
OK that code is working in my env for reading metadata!!

```rust
use symphonia::core::formats::FormatOptions;
use symphonia::core::io::MediaSourceStream;
use symphonia::core::meta::{MetadataOptions, MetadataRevision};
use symphonia::core::probe::Hint;

pub fn main() {
    let path: String = "D:\\Downloads\\twenor-libary\\public\\rick.mp3".to_string();
    let src = std::fs::File::open(&path).expect("failed to open media");
    let mss = MediaSourceStream::new(Box::new(src), Default::default());
    let mut hint = Hint::new();
    hint.with_extension("mp3");
    let meta_opts: MetadataOptions = Default::default();
    let fmt_opts: FormatOptions = Default::default();
    let mut probed = symphonia::default::get_probe()
        .format(&hint, mss, &fmt_opts, &meta_opts)
        .expect("unsupported format");

    if let Some(metadata_rev) = probed.format.metadata().current() {
        print_tags(&metadata_rev);
        if probed.metadata.get().as_ref().is_some() {
            println!("tags that are part of the container format are preferentially printed.");
            println!("not printing additional tags that were found while probing.");
        }
    } else if let Some(metadata_rev) = probed.metadata.get().as_ref().and_then(|m| m.current()) {
        print_tags(&metadata_rev);
    }
}

fn print_tags(metadata_rev: &MetadataRevision) {
    let tags = metadata_rev.tags();
    for (index, tag) in tags.iter().enumerate() {
        if tag.to_string().len() > 400 {
            continue;
        }
        println!("{}: {:?}", index, tag);
    }
}
```

So how now to Edit Metadata

How to rewrite A Tag for Example this one?

`5: Tag { std_key: Some(Genre), key: "TCON", value: String("Rap") }`

**Comment by SuisChan** [comment]
> How to rewrite

Symphonia doesn't support writing metadata (?), but alternatively you can look at this [lofty-rs](https://github.com/Serial-ATA/lofty-rs)

**Comment by pdeljanov** [comment]
Thank you @SuisChan for answering @cherob's question!

I'm going to close this, but feel free to re-open if there's any further problems.

**Comment by daniellga** [comment]
Hi @pdeljanov ! Isn't it worth to create an example out of this to put in [here](https://github.com/pdeljanov/Symphonia/tree/master/symphonia/examples)?
