### ISSUE TITLE
Some iTunes AAC files not played due to `malformed stream: isomp4: reserved bit not 1`

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#161]
`symphonia-play` refuses to play [this file](https://mega.nz/file/1l8UEKhR#9p_kTF9P2A6XqDWBbxyNKs7qMLAzVgsRyK-3fTK2WUU) with the following message:

```
 ERROR symphonia_play > file not supported. reason? malformed stream: isomp4: reserved bit not 1
```

This affects the entire album.

`ffplay` reports that this is AAC LC and plays the file successfully.

**Comment by pdeljanov** [comment]
This is fixed now!

**Comment by DoumanAsh** [comment]
@pdeljanov Can we have symphonia release with this fix?

**Comment by pdeljanov** [comment]
@DoumanAsh, I'm aiming to get something out in the next week or so, but need to go through a few PRs first that are taking some time.

**Comment by DoumanAsh** [comment]
Ok thank you, we'll use master branch for now I guess

**Comment by pdeljanov** [comment]
@DoumanAsh, v0.5.2 has been published!
