### ISSUE TITLE
Mismatches up to 1.06 on decoding some AAC files compared to FFmpeg

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#162]
I've run `symphonia-check --no-gapless` on a bunch of AAC files on commit f2bb002c92b528648bdacfb37b4ae77ede265239 and found some divergences from FFmpeg. I've included the ones from 0.1 upwards in [this archive](https://mega.nz/file/phs0XTDI#5ZYjVIwDlIiqjwWIINNY5oCLK8t_aDydaAPqxdxqZe0).

**Comment by pdeljanov** [comment]
Hey @Shnatsel,

All but two of these have been fixed since that commit. I'll take a look at the two broken ones soon.

Got anymore AAC files to test? I have about 450 in my collection. How many did you test to find those?

**Comment by Shnatsel** [comment]
I've tested 4636.

Extracting AAC from video would be a good source of test samples, see e.g. #105 for a promising corpus.

**Comment by Shnatsel** [comment]
I've re-tested on commit ed7b222a1c1ab3d26a0a4c6d402196c321a705d1 and the highest discrepancy is 0.000017, so all of these seem to be fixed. Thanks!

**Comment by pdeljanov** [comment]
That's true, `yt-dlp` seems to be able to evade throttling, but an issue with YouTube in general is that all videos use the same encoder, so it's a fairly homogeneous sample.
