### ISSUE TITLE
Metadata tag reading fails for non-utf8 mp3 tags

### ISSUE THREAD

**Issue by jbalintbiro** [pdeljanov/Symphonia#164]
I tried the following added to the `getting-started.rs` example after probing the media source:

```
     if let Some(mut meta) = probed.metadata.get() {
         if let Some(latest) = meta.skip_to_latest() {
             for tag in latest.tags().iter() {
                 println!("{:?}", tag);
             }
         }
     }
```

It works for mp3 files with utf8 tags, but it doesn't find anything for the ones in latin-2. Adding at least a fallback encoding would be great.

**Comment by pdeljanov** [comment]
Hi @jbalintbiro,

All the documented encodings (Latin-1, UTF-8, and UTF-16LE/BE per the ID3v2 spec.) should work. Are you able to provide the file so I can take a look? I only need the first MB or so.

**Comment by pdeljanov** [comment]
Sorry, since this is an issue never reported before I'll need a file to investigate. :(

Feel free to reopen the issue!
