### ISSUE TITLE
flac frame not parsed within FLAC_MAX_FRAME_HEADER_LEN bytes of file end

### ISSUE THREAD

**Issue by hcs64** [pdeljanov/Symphonia#165]
Because `read_fragments` doesn't work with less than FLAC_MAX_FRAME_HEADER_LEN + 1 bytes available, it will not be able to read the final fame of a file with a very small (e.g. constant) final frame, in some cases. Simple examples: [small last frame.zip](https://github.com/pdeljanov/Symphonia/files/10007470/small.last.frame.zip)

(Doesn't seem to be an issue anymore with f21afd5ed5e8e10c9db49a69f98a9b6b033f1d7c, which hit master as I was writing this.)

**Comment by pdeljanov** [comment]
Hi @hcs64, thanks for the samples, I've added them to my set of test vectors.

I can confirm that they are decoded correctly on my side too.

Cheers!
