### ISSUE TITLE
AIFF Support

### ISSUE THREAD

**Issue by Marekkon5** [pdeljanov/Symphonia#177]
Hello, would you consider adding AIFF audio support? Considering that there are no Rust crates, so only options are C libraries like libsndfile, I believe this would be a great addition.

Thank you.

**Comment by pdeljanov** [comment]
Hi @Marekkon5,

I'm open to including it, however, I think I want to leave it for a contributor to work on. It's a relatively simple format (on par with WAVE), so it's a good intro to the project.

Some information about this format can be found [here](https://www.mmsp.ece.mcgill.ca/Documents/AudioFormats/AIFF/AIFF.html).

Related issue #75.

**Comment by Marekkon5** [comment]
@dedobbin I have found https://crates.io/crates/pacmog which has AIFF decoder, so maybe that helps, but I have no experience with the Symphonia "ecosystem".

**Comment by pdeljanov** [comment]
AIFF support is now implemented in abb3aab by @dedobbin, please give it a try!

**Comment by dedobbin** [comment]
Please note that as it turns out a lot of AIFF files are in fact AIFC files (an extended format supporting more features, like compression). Locally i added support for playing these compressed files, but i need to test more before i will make a PR for that

**Comment by pdeljanov** [comment]
Closing since this is done now, thanks @dedobbin!
