### ISSUE TITLE
Question: Is it possible to edit mp3 audio, i.e. cutting out durations? 

### ISSUE THREAD

**Issue by Asim-A** [pdeljanov/Symphonia#178]
Hi, I 
Disclaimer: _I have never worked with audio processing so I am unsure about the terminology, please correct me or ask for clarifications if something is incorrect or if there is a misunderstanding._

Challenge: 
I have a lot of audio files (.mp3) and a database with durations for each audio file. The durations are an array of start and end time in seconds. I want to cut those from the respective audio file, that is to remove them from the file e.g. per audio file: 
```{
  "durations": [
    { "start": 0, "end": 23 },
    { "start": 55, "end": 64 },
    { "start": 75, "end": 99 },
    ...
  ],
  "unit": "seconds"
}
```

Is this possible with Symphonia, and if so, are there any examples?

**Comment by pdeljanov** [comment]
For playback it should be possible by just looking at the timestamps Symphonia gives you. If you want to write it out to a new file then that's not possible right now since we only support decoding. I'd recommend `ffmpeg` in the latter case.

**Comment by Asim-A** [comment]
Okay, thank you:)
