### ISSUE TITLE
Seeking to a postion other than zero decodes from the wrong position

### ISSUE THREAD

**Issue by BillyDM** [pdeljanov/Symphonia#19]
In creating my real-time disk-streaming crate, I've noticed that calling `reader.seek()` doesn't start decoding from the correct position, instead it seems to start decoding a bit after the requested position. I've only tested this on `wav` files so far.

This is the code I have for my `seek_to` function:

```rust
pub fn seek_to(&mut self, frame: usize) -> Result<(), ReadError> {
    self.current_frame = frame;

    let seconds = self.current_frame as f64 / f64::from(self.sample_rate.unwrap_or(44100));

    self.reader.seek(SeekTo::Time {
        time: seconds.into(),
    })?;

    self.reset_smp_buffer = true;
    self.curr_smp_buf_i = 0;

    Ok(())
}
```

I noticed that if `frame` is 0, than it correctly starts decoding from the start of the file. But any frame other than 0, it starts decoding from a bit ahead of the given frame.

I've checked the output of `reader.seek()`, and it returns the same amount of seconds as I put in for a `wav` file. I know I'll have to keep track of this for other codecs, but I'm just trying to get `wav` to work for now.

Maybe this has something to do with the `reader.seek()` function not using the proper sample rate?

**Comment by pdeljanov** [comment]
Do you know many frames it is off by?

I may have found an issue that would affect the second, third, fourth, and so on seeks on the WavReader, but not the first.

Can you confirm that the first seek is broken by seeking to a time > 0.0? If your first seek is broken then I may need a sample file because I can't reproduce it on my end unfortunately.

**Comment by BillyDM** [comment]
Actually, it does work correctly the first time it seeks. It's when my code loops around and calls seek again when it happens.

**Comment by pdeljanov** [comment]
Gotcha, should be fixed now!

**Comment by BillyDM** [comment]
Sweet, it's working now! Thanks!
