### ISSUE TITLE
Unable to open a 12 channel wav file

### ISSUE THREAD

**Issue by ModProg** [pdeljanov/Symphonia#192]
Unable to open the attached audio files with symphonia's `WavReader`.

- audio_array_benchmark2.wav resulted in `wav: channel layout is not stereo or mono for fmt_ieee`
- audio_array_benchmark2.alt.wav resulted in `wav: channel layout is not stereo or mono for fmt_pcm`

I created the `.alt` file because I found that I could open that one using https://crates.io/crates/hound while it failed on the first one as well.

[audio_array_benchmark2.zip](https://github.com/pdeljanov/Symphonia/files/10888433/audio_array_benchmark2.zip)

The audio file is from a dataset found here (https://zenodo.org/record/3630471)

**Comment by dedobbin** [comment]
Both files play after this commit:
https://github.com/pdeljanov/Symphonia/commit/cd6a5dbd8836e9c69f4804e5f42fa9b4ba183d5e

So this should be fixed up an upcoming release
