### ISSUE TITLE
`AudioBuffer::make_equivalent` behavior surprising

### ISSUE THREAD

**Issue by SolraBizna** [pdeljanov/Symphonia#198]
I lost some time today because I assumed calling `buf.make_equivalent()` would give me a converted audio buffer of the destination type. I was surprised when I found that it makes an audio buffer of the destination type, with the correct number of channels and allocation size, but then just returns the new buffer empty. To get the behavior I expected, I needed to call `buf.convert(&mut returned_buf)` afterward. If this is intended, I'd like it if the documentation were clearer about this.

**Comment by pdeljanov** [comment]
Thanks for the feedback. This function is going to be removed in the new major release.
