### ISSUE TITLE
When will the fix to wav files be published to crates.io?

### ISSUE THREAD

**Issue by BillyDM** [pdeljanov/Symphonia#20]
I finally have reading and writing wav files fully functional in my realtime disk streaming crate. https://github.com/RustyDAW/rt-audio-disk-stream

I would like to publish this to crates.io, but right now it is relying on the git version of Symphonia because of that wav problem we had earlier. I just wondered when you could get this updated? Please and thanks!

**Comment by pdeljanov** [comment]
I wasn't planning to push a new version till I landed some more changes, but I'll try to find some time in the next few days to do one.

**Comment by BillyDM** [comment]
Alright, thanks! No rush, I just wanted to know when this was planned.

**Comment by pdeljanov** [comment]
Done! Enjoy :smile: !
