### ISSUE TITLE
Panic with wav files

### ISSUE THREAD

**Issue by qarmin** [pdeljanov/Symphonia#200]
```
thread 'main' panicked at 'index out of bounds: the len is 89 but the index is 184', /home/rafal/.cargo/git/checkouts/symphonia-8fbe6c90fc095688/b4ef823/symphonia-codec-adpcm/src/codec_ima.rs:51:20
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/std/src/panicking.rs:575:5
   1: core::panicking::panic_fmt
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:64:14
   2: core::panicking::panic_bounds_check
             at /rustc/2c8cc343237b8f7d5a3c3703e3a87f2eb2c54a74/library/core/src/panicking.rs:159:5
   3: symphonia_codec_adpcm::codec_ima::decode_mono
   4: <symphonia_codec_adpcm::AdpcmDecoder as symphonia_core::codecs::Decoder>::decode
   5: symphonia::main
```

[Broken.zip](https://github.com/pdeljanov/Symphonia/files/11163101/Broken.zip)

**Comment by dedobbin** [comment]
Hey!  I'm kinda looking into this.
It should definitely not crash, but when i play these files in audacity it also doesn't sound quite uh.. healthy.
Is there any context to these files? Is that the sound it's supposed to make ?

**Comment by qarmin** [comment]
In my app I have option to find broken files, so users can find really strange files that crashes this library in many ways,  so I try to find the files myself.

This files were found by fuzzer, so music inside probably is broken.

**Comment by dedobbin** [comment]
From what i've seen while playing around, it plays some samples correct, but eventually reads an invalid value, which should be the key for the step table in `symphonia-codec-adpcm/src/codec_ima.rs` 

I traced the code, to see if anything is off spec for ADPCM decoding. I found some leads but nothing definite.
