### ISSUE TITLE
Issues decoding a PCM stream 

### ISSUE THREAD

**Issue by Lighty0410** [pdeljanov/Symphonia#210]
Hey everyone! I'm trying to decode a pcm live stream but i can't seem to figure out how to do so. 

My pipeline: 
1) Feed the .wav stream to the ffmpeg demuxer. 
2) Implement a custom unseekable reader so i can push the data from the demuxer to the reader. 
2) Get the `pcm_s16le` chunk of data from the ffmpeg demuxer (i need this because in the real world use case i transcode from aac to pcm_s16le). 
4) Push the data to the symphonia reader. 

And here comes the issue. For some reasons using the `pcm_s16le` codec i can't seem to decode the stream. I face the next errors: 
```
[2023-05-29T16:18:12Z WARN  symphonia_bundle_mp3::demuxer] skipping junk at 258418 bytes
[2023-05-29T16:18:12Z WARN  symphonia_bundle_mp3::demuxer] skipping junk at 259354 bytes
[2023-05-29T16:18:12Z WARN  symphonia_bundle_mp3::demuxer] skipping junk at 259522 bytes
[2023-05-29T16:18:12Z WARN  symphonia_bundle_mp3::demuxer] invalid mpeg audio header
[2023-05-29T16:18:12Z WARN  symphonia_bundle_mp3::demuxer] invalid mpeg audio header
[2023-05-29T16:18:12Z WARN  symphonia_bundle_mp3::demuxer] invalid mpeg audio header
[2023-05-29T16:18:12Z WARN  symphonia_bundle_mp3::demuxer] invalid mpeg audio header
[2023-05-29T16:18:12Z WARN  symphonia_bundle_mp3::demuxer] invalid mpeg audio header
```
I tried using `hint.extension("pcm")` but it doesn't seem to do anything. It still detects the stream as an `mp3` container. 

However using all the same pipeline with the `aac` codec works absolutely fine. It kinda bugs me and i don't understand why.  

Repro:

For .wav stream:  

1) Create a .wav file using ffmpeg - 
`ffmpeg -f alsa -i hw:1 -t 10 -codec pcm_s16le -ar 16000 recorded.wav` (i'm just recording audio using the micro) 
2) Run the [example](https://gist.github.com/Lighty0410/6f80bcab870bb4929d6274515081c38f)
^ doesn't work

For .aac stream: 

1) Create an .aac file using ffmpeg - 
`ffmpeg -f alsa -i hw:1 -t 10 -codec aac -ar 16000 recorded.aac` (i'm just recording audio using the micro) 
2) Run the [example](https://gist.github.com/Lighty0410/6f80bcab870bb4929d6274515081c38f) (it's the same) 
^ works 

I'm trying to wrap my head around for several days and any help will be much appreciated!

**Comment by pdeljanov** [comment]
If I understand correctly, you're using FFmpeg to demux your audio and then passing the packets to Symphonia for decoding. If so, the issue is that the example is trying to do both demuxing and decoding with Symphonia.

When you have a WAVE file that contains uncompressed PCM audio, the audio packets are just the raw PCM samples. So when Symphonia tries to determine what audio format it is to select a demuxer (aka a `FormatReader`), it just happens to land on a MP3 demuxer because the raw PCM audio data just so happened to look like a MP3 file.

Essentially, you want to skip the demuxing step with Symphonia entirely. To do this you can instantiate a `PcmDecoder` manually and convert the FFmpeg packets to Symphonia `Packet`s.

I didn't quite understand why you need FFmpeg to do the demuxing, though. Take a look at the the `symphonia-check` utility. It spawns a `ffmpeg` process and pipes the output WAVE to Symphonia. This works fine because Symphonia does the demuxing. Perhaps that utility can give you some ideas?

As for why AAC works: your `ffmpeg` command line for AAC creates an AAC file using the [ADTS](https://wiki.multimedia.cx/index.php/ADTS) format. It looks like FFmpeg passes the ADTS packets straight through to the decoder without removing the ADTS headers. Therefore, since Symphonia has an ADTS demuxer, it is able to select the ADTS demuxer and everything works as intended.

**Comment by Lighty0410** [comment]
> If I understand correctly, you're using FFmpeg to demux your audio and then passing the packets to Symphonia for decoding. If so, the issue is that the example is trying to do both demuxing and decoding with Symphonia.
> 
> When you have a WAVE file that contains uncompressed PCM audio, the audio packets are just the raw PCM samples. So when Symphonia tries to determine what audio format it is to select a demuxer (aka a `FormatReader`), it just happens to land on a MP3 demuxer because the raw PCM audio data just so happened to look like a MP3 file.
> 
> Essentially, you want to skip the demuxing step with Symphonia entirely. To do this you can instantiate a `PcmDecoder` manually and convert the FFmpeg packets to Symphonia `Packet`s.
> 
> I didn't quite understand why you need FFmpeg to do the demuxing, though. Take a look at the the `symphonia-check` utility. It spawns a `ffmpeg` process and pipes the output WAVE to Symphonia. This works fine because Symphonia does the demuxing. Perhaps that utility can give you some ideas?
> 
> As for why AAC works: your `ffmpeg` command line for AAC creates an AAC file using the [ADTS](https://wiki.multimedia.cx/index.php/ADTS) format. It looks like FFmpeg passes the ADTS packets straight through to the decoder without removing the ADTS headers. Therefore, since Symphonia has an ADTS demuxer, it is able to select the ADTS demuxer and everything works as intended.

Thank you A LOT. Now it works :). 
I have one question left. 
There's the function to create a packet from a slice: 
`pub fn new_from_slice(track_id: u32, ts: u64, dur: u64, buf: &[u8])` 
If i fill everything except for the buffer with 0s it works fine and everything is alright. However, i'm curious whether it could affect anything or not in my case since i'm manually decoding each and every packet?

>I didn't quite understand why you need FFmpeg to do the demuxing, though. Take a look at the the symphonia-check utility. It spawns a ffmpeg process and pipes the output WAVE to Symphonia. This works fine because Symphonia does the demuxing. Perhaps that utility can give you some ideas?

I'm demuxing a .wav file here for the sake of simplicity. In a real life scenario i'm demuxing an mpeg-ts stream, transcode the AAC stream to pcm_s16le, then decode it to `f32` samples using `Symphonia` then feed it to `whisper-gcc` In real time. Btw, this is the prototype and maybe it will be useful for someone in a future: 
[prototype](https://gist.github.com/Lighty0410/ed2d452c3cb318b974170e37ce4bbe52)

**Comment by pdeljanov** [comment]
> If i fill everything except for the buffer with 0s it works fine and everything is alright. However, i'm curious whether it could affect anything or not in my case since i'm manually decoding each and every packet?

This is fine for `PcmDecoder`. However, some other decoders (generally for the lossy codecs) use the duration to trim the decoded audio buffer for gapless playback.

> I'm demuxing a .wav file here for the sake of simplicity. In a real life scenario i'm demuxing an mpeg-ts stream, transcode the AAC elementary stream to pcm_s16le, then decode it to f32 samples using Symphonia then feed it to whisper-gcc In real time. Btw, this is the prototype and maybe it will be useful for someone in a future:

Ah, I see. So you want to use `ffmpeg` because Symphonia doesn't have a MPEG-TS demuxer?
