### ISSUE TITLE
How to convert to an i16 mono sample

### ISSUE THREAD

**Issue by AlejandroCabeza** [pdeljanov/Symphonia#212]
Hi!

I'm quite new to audio, and even more so to Symphonia. I'm trying to make use of another library which requires audio samples in i16 mono. I followed the example using a i16 mono audio file, and it works just fine. The issues appear when I try to use a file with different specs (e.g. f32, stereo). I've spent quite some hours trying to read and convert the samples from one spec to the other without any success.

Is there some way to achieve this way with the library, or should I switch?

**Comment by DavidVentura** [comment]
I am in the same situation, which example did you end up using?
