### ISSUE TITLE
Vorbis decoder panics with end of stream 

### ISSUE THREAD

**Issue by dvdsk** [pdeljanov/Symphonia#235]
The ogg test file in [rodio](https://github.com/RustAudio/rodio/issues/516) breaks symphonia. When running the example code (modified with type hint `.ogg`) it crashes with:

```
thread 'main' panicked at src/main.rs:67:17:
end of stream
```

I have attached the file:
[music.zip](https://github.com/pdeljanov/Symphonia/files/12881956/music.zip)
You can also download it directly from:
https://github.com/RustAudio/rodio/blob/master/assets/music.ogg

It only broke a test, its not blocking me, feel free to give this a low priority.

**Comment by pdeljanov** [comment]
Based the output you provided, it looks like Symphonia returned an end-of-stream error that wasn't handled by the application. I also don't get any panics when I decode the file with `symphonia-play`. So I'm not sure this is a bug. Could you provide a backtrace?

**Comment by dvdsk** [comment]
> Based the output you provided, it looks like Symphonia returned an end-of-stream error that wasn't handled by the application. 

Ill be honest, I do not fully understand what the Rodio code is doing. On first glance it seems like the Symphonia decoder is immediately returning end-of-stream. The use of Symphonia in Rodio wildly differs from the examples provided by Symphonia. I'am in the process of clarifying/refactoring that code. 

Once that's done Ill take another look, if the issue is still there ill reopen.
