### ISSUE TITLE
Opus probe panics with `unsupported format: DecodeError("ogg: packet buffer would exceed max size")`

### ISSUE THREAD

**Issue by Curstantine** [pdeljanov/Symphonia#237]
I think this in an edge case of sorts. The track attached works fine with ffprobe and other music players, but errors with:

```
thread 'utils::symphonia::test::test_read_track_meta' panicked at 'unsupported format: DecodeError("ogg: packet buffer would exceed 
max size")'
```

Code:
```rust
let mut probed = symphonia::default::get_probe()
	.format(&hint, mss, &fmt_opts, &meta_opts)
	.expect("unsupported format");
```

File: [01 守護霊.zip](https://github.com/pdeljanov/Symphonia/files/12909282/01.zip)

**Comment by pdeljanov** [comment]
Thanks for the report.

The album artwork on the file was of extremely high quality and hit a limit placed on the maximum size. This limit will be configurable in the future with API updates, but for now I've doubled the limit and the file should work.

**Comment by andrewbaxter** [comment]
Has this been parameterized as `symphonia::core::io::MediaSourceStreamOptions { buffer_len: 8 * 1024 * 1024 * 1024 }`, or is that a separate parameter?

I have a vorbis ogg with 3000x3000 cover art and I'm getting the same error, but bumping the max buffer length up to (I think?) 8gb doesn't seem to help things.

**Comment by andrewbaxter** [comment]
Hmm, this didn't help either
```
            &symphonia::core::meta::MetadataOptions {
                limit_metadata_bytes: symphonia::core::meta::Limit::Maximum(1024 * 1024 * 1024),
                limit_visual_bytes: symphonia::core::meta::Limit::Maximum(1024 * 1024 * 1024),
            },
```

The audio file is 27MB and IIUC the cover is compressed, is symphonia decompressing it or something?
