### ISSUE TITLE
(Feature request) Video support on symphonia-play

### ISSUE THREAD

**Issue by hardBSDk** [pdeljanov/Symphonia#238]
It would make `symphonia-play` equivalent to the `ffplay` from ffmpeg, the video support could be implemented using the window library `winit` for a better cross-platform support, as it offer window support beyond X11/Wayland.

**Comment by pdeljanov** [comment]
I like the idea of supporting video playback, however, I don't have the bandwidth to take that on. I'm open to people experimenting with it and seeing where we need to make changes (e.g., trait definitions, etc.) to support it.

**Comment by hardBSDk** [comment]
@pdeljanov When I asked this question I was not aware that Symphonia is audio-only, video-rs seems more appropriate for my request.
