### ISSUE TITLE
Missing cover visuals in certain opus files

### ISSUE THREAD

**Issue by Curstantine** [pdeljanov/Symphonia#245]
ffprobe run returns a valid cover visual, which symphonia `meta_rev.visuals()` does not.
![image](https://github.com/pdeljanov/Symphonia/assets/69104500/96b93b04-71fe-4c72-aad1-224ad44433fd)

File: [01 Victim.zip](https://github.com/pdeljanov/Symphonia/files/13763894/01.Victim.zip)

**Comment by pdeljanov** [comment]
Thanks for reporting. Support was added!
