### ISSUE TITLE
Provide an error to properly indicate EOF

### ISSUE THREAD

**Issue by ahicks92** [pdeljanov/Symphonia#246]
I'm integrating Symphonia, and the only thing I can find on detecting EOF is the symphonia-play example, which is going as far as a string comparison on an error message.  It seems like either FormatReader's next_packet should return `Option<Packet>`, or there should be a top-level error.  Hopefully this isn't a duplicate of something or docs I'm missing.

**Comment by pdeljanov** [comment]
This is a very popular request, and one that I fully support. Since it's a breaking API change it will come in version 0.6. :)

**Comment by ahicks92** [comment]
Did I miss a duplicate ticket? I did look.

How involved would this be? If the answer is "not very" I may be willing to help, but I barely have time for my own projects as it is.

**Comment by hasezoey** [comment]
i think relevant would be #134

**Comment by pdeljanov** [comment]
This has now been implemented in the `dev-0.6` branch!
