### ISSUE TITLE
[Feature Request]: get all streams of file from probe

### ISSUE THREAD

**Issue by singersbalm** [pdeljanov/Symphonia#248]
i noticed that the tags of metadata in the probe contain the bps, byte size, number of frames and duration.
The audio data can be extracted with tracks. i want to know if its possible to add a function that returns the stream with the data codec name/type, bps/bitrate, size, duration, start_time, width, height, lang and which stream it is in the file.

**Comment by pdeljanov** [comment]
The metadata returned during a probe is the metadata that was encountered *before* the media container begins. This is mostly for MP3 where tags are just a blob of binary data appended to the start of the file.

To obtain track and codec information, as well as any metadata contained within the media container, you need to get the format reader. Probe provides the `format` function to quickly get this.
