### ISSUE TITLE
style: `symphonia_format_mkv::ebml` prints a lot of `element with tag: A3`

### ISSUE THREAD

**Issue by hasezoey** [pdeljanov/Symphonia#259]
I had just enabled feature `mkv`, and using any file (mkv, mka, webm) it will print a *lot* of `element with tag: A3` compared to other formats / codecs which dont print so much.

i know this can be disabled via logs, but i wanted to mention it here because it prints that like ~46 times a second and the other codecs (like mp3) dont do this.

i tested this with `mkv`(video + audo stream), `mka` (audio stream) and `webm`(video + audio stream), also completely stripped of other metadata (generated via ffmpeg)

**Comment by pdeljanov** [comment]
Sure, that is pretty annoying. Thanks!
