### ISSUE TITLE
[Doc request] Multi-value tags in metadata

### ISSUE THREAD

**Issue by andrewbaxter** [pdeljanov/Symphonia#268]
In some media tags can have multiple values.  Looking at the documentation of `tags()` and `Tag` there's no mention of this, and `tag.value()` is a single string not an array.

In the code it's somewhat documented (if a user wants to dig that far): https://github.com/pdeljanov/Symphonia/blob/master/symphonia-metadata/src/id3v2/frames.rs#L647

I have one other question, which is whether the tag value order is preserved.  I see the tag is `push` ed so I assume it's an insertion-order container, but I'm not sure if additional processing happens afterward.

**Comment by pdeljanov** [comment]
Hi @andrewbaxter,

Thanks for the feedback, I updated the documentation to make a note about multiple values being stored across multiple `Tag`s.

> I have one other question, which is whether the tag value order is preserved. I see the tag is `push` ed so I assume it's an insertion-order container, but I'm not sure if additional processing happens afterward.

It would be preserved. A metadata reader can only append onto a metadata revision which is then passed to you directly without any additional processing.

Hope this helps!

**Comment by andrewbaxter** [comment]
Awesome, thank you!
