### ISSUE TITLE
Update benchmarks following v0.5.4

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#269]
The [BENCHMARKS.md](https://github.com/pdeljanov/Symphonia/blob/master/BENCHMARKS.md) file has been last updated in February 2023, but the [v0.5.4 release](https://github.com/pdeljanov/Symphonia/releases/tag/v0.5.4) lists performance improvements to many codecs. It would be great to see the performance improvements reflected in the benchmarks.

**Comment by pdeljanov** [comment]
That's not really necessary, the benchmarks were updated after all those changes were made. It's just been a very long time since the last Symphonia release. :)
