### ISSUE TITLE
Issue parsing AIFF files: "invalid chunk-id, expected 'FORM'" and "FourCC contains invalid characters: 02 87 04 06"

### ISSUE THREAD

**Issue by mxw-meta** [pdeljanov/Symphonia#270]
Hey Folks 👋

First off, thanks for the most recent release. The added AIFF support was something me and my team have been looking out for!
We did some testing, and encountered some erroneous AIFF files (from freesound), that import fine in Audacity and other DAWs. I thought I'd share the files so you could take a look and decide if the files are considered broken, or if they could help harden the product.

[broken_AIFFs.zip](https://github.com/pdeljanov/Symphonia/files/14460514/broken_AIFFs.zip)
contains:
- 58920__mattwasser__retro-game-jingle.aiff, causing `FourCC contains invalid characters: 02 87 04 06`
- 570717__canimalsozseries__jumping.aiff, causing `invalid chunk-id, expected 'FORM'`

Thanks again for your continuous efforts on this crate! I hope bringing in these examples helps out.

**Comment by pdeljanov** [comment]
@dedobbin could you take a look?

**Comment by dedobbin** [comment]
Hey !

First of all, glad to hear you enjoy the AIFF support.

I checked the files, they play properly for me using symphonia-play. Could you double check if these are indeed the offending files? 
If they do are, i'm curious what platform you used to build Symphonia on?

**Comment by mxw-meta** [comment]
Oh, that's interesting. We can verify that they actually parse fine outside of the product.
This may, or may not be related to this crate then. I can close for now until we have something reproducible.

Sorry for stealing your time! I should have made sure I can repro locally first.
