### ISSUE TITLE
ApeV2 tags at the end of an MP3 file are not read

### ISSUE THREAD

**Issue by Tormak9970** [pdeljanov/Symphonia#286]
I have a .mp3 file with Apev2 tags at the end of it, and given Symphonia's MP3 status I would have expected it to read them. Most other tools I've tried successfully read it as well (mp3tag, various online tools, etc). Its possible I've missed something and this is possible already, but I don't think so

**Comment by pdeljanov** [comment]
APE tag support is now implemented in the `dev-0.6` branch, however it will probably be a bit longer before that branch is ready to be merged to the main branch.
