### ISSUE TITLE
feature request for apple's lossless format

### ISSUE THREAD

**Issue by jsomedon** [pdeljanov/Symphonia#32]
Any plan on supporting apple's lossless format(as m4a file)?

**Comment by pdeljanov** [comment]
I've been considering it, though probably after Vorbis and maybe Opus. Is it (or has it been) possible to download ALAC files off iTunes? I'm not sure where else someone would normally get ALAC files from.

**Comment by jsomedon** [comment]
iirc itunes doesn't offer ALAC as downloadable format. I know bandcamp does offer ALAC download though. For example this album is free to download on bandcamp: https://neoncityrecords.bandcamp.com/album/sailor-team-hits

**Comment by pdeljanov** [comment]
Hey @jsomedon,

If you're still interested, I've added ALAC support.

The decoder is _very_ fresh, but I've had excellent results on the files I have/found. Of course, more testing is always appreciated.

If you want to test, you can use `symphonia-check` to compare Symphonia's decoded output to `ffmpeg` (you'll need FFMpeg installed). You can also use `symphonia-play` to just play it. I'd recommend checking the file first before playing :wink: .

Enjoy!

**Comment by jsomedon** [comment]
I didn't expect that the ALAC support would come this fast, what a surprise! 😮 😄 

So I ran `symphonia-check` with [this song](https://neoncityrecords.bandcamp.com/track/macross-82-99-sailor-team) and I got this error:
```
Test interrupted by error: unsupported feature: core (codec):unsupported codec
```

The song plays fine with `symphonia-play` though.

FYI, I attached that song file here.
[Sailor Team - Sailor Team Hits! - 01 Macross 82-99 - Sailor Team.m4a.zip](https://github.com/pdeljanov/Symphonia/files/7528595/Sailor.Team.-.Sailor.Team.Hits.-.01.Macross.82-99.-.Sailor.Team.m4a.zip)

**Comment by pdeljanov** [comment]
Whoops, I forgot to enable the `alac` feature on the `symphonia` dependency for `symphonia-check`. It is fixed now.

Kinda weird, if you run `cargo run --bin symphonia-check` in the workspace root then ALAC support got enabled for `symphonia-check`, but if you run it in the symphonia-check/ directory, it did not. I guess in the former case, Cargo saw that `alac` was enabled for `symphonia-play` and enabled it for everything.

I wonder if this an expected behaviour of Cargo or a bug? I usually run the binaries in the workspace root so that's why I missed enabling the feature. :confused:

**Comment by jsomedon** [comment]
> Kinda weird, if you run `cargo run --bin symphonia-check` in the workspace root then ALAC support got enabled for `symphonia-check`, but if you run it in the symphonia-check/ directory, it did not.

That's exactly how I got the error above.. 😅 I guess it's probably some cargo thing like you said. 😕 I just tested in the root dir and everything works fine! 🥳

**Comment by pdeljanov** [comment]
Sounds good! I'm going to close this issue, but feel free to raise a new one if you encounter any issues.
