### ISSUE TITLE
Incorrect value used to construct SampleWriter

### ISSUE THREAD

**Issue by Herohtar** [pdeljanov/Symphonia#38]
`SampleWriter::from_buf` uses an unsafe code block to create a mutable slice, [with `buf.capacity()` as the length](https://github.com/pdeljanov/Symphonia/blob/81e9d5c31d3cbfd0ee51ebd969d264794efa875b/symphonia-core/src/audio.rs#L960); however, it seems the intention is for the referenced slice to be of length `n_samples`. It appears that the method is always called with `n_samples` equal to `buf.capacity()`, but it could cause unintended behavior if the code is ever called with a different value.

**Comment by pdeljanov** [comment]
This is indeed an issue. Good catch!

The purpose of `SampleWriter` and the `WriteSample` trait was to write `Sample`s from an `AudioBuffer` into a `RawAudioBuffer` as raw bytes. In C/C++, it'd be possible to just allocate a buffer and cast the buffer pointer to the actual sample data type (u24 being the exception) and then copy the samples, or even just use a memcpy. This code was trying to emulate that implementation in Rust for "performance." However, I now think a safe implementation would be just as fast and cleaner.

Therefore, I actually think this part of the code needs to be rewritten entirely. Once this is rewritten safely then the library will be 100% safe Rust.

Is this something you would be interested in taking on?

**Comment by Herohtar** [comment]
I was actually initially hoping to be able to replace both instances of unsafe code, which is how I discovered that issue. My existing Rust knowledge wasn't sufficient for me to determine a solution right away and my brief research into it only resulted in more unsafe methods, but I'd definitely be interested in continuing to look into rewriting it.
