### ISSUE TITLE
Add library to compare similarity of music files

### ISSUE THREAD

**Issue by qarmin** [pdeljanov/Symphonia#50]
I wanted to add support to my app to find similar music(by content, not tags).

For images I use [img_hash](https://github.com/abonander/img_hash) which generate 64(and later maybe even 128) bit hash which I save to special tree [bk-tree](https://github.com/eugene-bulkin/rust-bk-tree) which allow to get similar hashes(similar hashes are generated for similar images).

I wanted to use [chromaprint](https://github.com/acoustid/chromaprint) for this but since my app is multiplatform and support also Windows and MacOS, there could be a problem with exporting app to this OS and also music decoding.

**Comment by pdeljanov** [comment]
It's a neat idea, but audio fingerprinting would be out of scope for Symphonia. I'd imagine an audio fingerprinting library using Symphonia to decode the audio and then applying its own algorithms rather than those algorithms being part of Symphonia.
