### ISSUE TITLE
Vorbis: Neverball audio files are cut short

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#54]
The following files from the open-source game Neverball are cut short when played using `symphonia-play`. The last half-second or so is not played, and an error is printed. By contrast, VLC plays the entire file - and the original game did too, back when I played it.

[neverball-problematic-vorbis.tar.gz](https://github.com/pdeljanov/Symphonia/files/7165563/neverball-problematic-vorbis.tar.gz)

**Comment by pdeljanov** [comment]
Thanks, great find!
