### ISSUE TITLE
Matroska / WebM support

### ISSUE THREAD

**Issue by darksv** [pdeljanov/Symphonia#63]
Hello. 

I noticed you have plans to add support for MKV / WebM containers. Is there anybody actively working on this? I think I might be able to find some time to help.

**Comment by pdeljanov** [comment]
Hi @darksv,

No one has reached out to me about working on MKV/WebM support, and I personally wasn't planning to work on it anytime soon. It'd be a great and welcome addition if you can find the time.

I do believe the format is quite a bit more involved than others, so feel free to reach out if you have any questions, need guidance, etc.

Cheers!
