### ISSUE TITLE
MP3 decoding mismatch with ffmpeg (max delta above 1)

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#69]
I had a sample that triggered exactly 2.0 discrepancy but I have accidentally destroyed it when trying to tar them in bulk :sob: 

Samples with max delta above 1 according to `symphonia-check`: [link](https://drive.google.com/file/d/12qZr8-zC-sshbjbfe6rJS5MwBd_0KaDn/view?usp=sharing)

Tested on commit a723c15c7ff7181ac4c1c729edff271dcef96d2e

**Comment by pdeljanov** [comment]
Hey @Shnatsel,

These all appear to be false positives. These files are damaged and FFMpeg seems to discard an extra packet/samples whereas Symphonia does not. This causes the two outputs to become "mis-aligned" resulting in the huge mismatches. If you try a different reference decoder such as mpg123 ([uncomment these lines](https://github.com/pdeljanov/Symphonia/blob/a723c15c7ff7181ac4c1c729edff271dcef96d2e/symphonia-check/src/main.rs#L75-L83)), the files pass with only one exception.

There are a couple errors with the file even with mpg123 after the error, but ultimately there is no prescribed method for dealing with corrupt streams so I don't believe there is an issue here unless. When played back they sound the same.

**Comment by Shnatsel** [comment]
I see. Thanks!

**Comment by Shnatsel** [comment]
Is there any way I can detect such damaged files in the future? I have a few more files with errors, but I wouldn't want to file bugs about false positives.

**Comment by Shnatsel** [comment]
I've tried mpg123, but that just causes 2.0 mismatches on other files.

**Comment by pdeljanov** [comment]
If the files are failing badly on *both* `ffmpeg` and `mpg123`, then that's a signal that Symphonia may not be handling errors as optimally as it should. I'd be interested in seeing these cases, even if only a few.

However, if the files that fail on `ffmpeg` are different than those that fail with `mpg123` then there's likely nothing really wrong. These two decoders don't always agree with each other. I actually even tried a third decoder, `mpg321`, which is based on `libmad`, and it disagrees with the other two many times lol...

A nice solution would be having `symphonia-check` be able to detect these mismatches and report which packets were dropped. When you look at the `[FAIL]` messages, you'll notice in these cases that either Symphonia or the reference decoder are simply offset from each other. For example, the first sample in packet 10 of the reference decoder is equal to the first sample in packet 5 of Symphonia. In this case, Symphonia dropped 5 packets.
