### ISSUE TITLE
MP3: Mismatch with delta 0.0004 on MySpace Dragon Hoard corpus

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#70]
Following the fix for #68, there is a single mismatch above the 0.00002 threshold on the [MySpace Dragon Hoard](https://archive.org/details/myspace_dragon_hoard_2010) corpus. The max delta is 0.00042961, the file is attached:
[std_9dc496596e1558362a28966aacdab41d.mp3.gz](https://github.com/pdeljanov/Symphonia/files/7608893/std_9dc496596e1558362a28966aacdab41d.mp3.gz)

Tested vs ffmpeg version 4.2.4-1ubuntu0.1 built with gcc 9 (Ubuntu 9.3.0-10ubuntu2)

Tested on commit 16497ee5fb0d2f00287ba3444c52b22bc4debdae

**Comment by pdeljanov** [comment]
This was an interesting find, because there was a small bug in Symphonia, however the proper fix in my opinion would deviate from both `ffmpeg` and `mpg123`. For now I've chosen to just do as they do but print a different message instead.

**Comment by Shnatsel** [comment]
Wow! Thanks for the quick fix!

I'm surprised this was actually actionable :grin: 

I'll re-run `symphonia-check` on my other MP3s shortly.

**Comment by pdeljanov** [comment]
No problem. On a side note, I think I actually a bug in `ffmpeg` regarding this issue. This may cause you to get failures when you test more MP3s.

If you see `count1 overrun, malformed bitstream` or `big_values overrun, malformed bitstream` and get a failure, check if it also fails with `mpg123`. If it doesn't then I think we're good.
