### ISSUE TITLE
AIFF support

### ISSUE THREAD

**Issue by Be-ing** [pdeljanov/Symphonia#75]
Uncompressed PCM data is sometimes stored in AIFF files rather than WAV. It would be nice to add support for this.

**Comment by pdeljanov** [comment]
This is something that'd be nice to have. I might be able to get around to it in a future release, but it might be a while unless anyone would like to contribute!

**Comment by pdeljanov** [comment]
Closing since this was added!

**Comment by Be-ing** [comment]
Nice, thanks for the update!
