### ISSUE TITLE
FLAC: mismatches with max delta > 1.9 on a handful of packets per file

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#76]
[These 3 FLAC files](https://mega.nz/file/BtciERiK#bA74_sZweR8Iin0w-ubcxq1i4RX-OeEvGspiYqIEqDs) exhibit large mismatches (max delta > 1.9) compared to ffmpeg.

Only a handful of packets (1 to 10) are affected, and the affected packets are not sequential, so it does not appear to be caused by misalignment.

Tested on commit f05f310a73d3f8bad0bfe1fa2c6982e93b146f13 (the latest one as of this writing).

Only these 3 files out of ~10,000 (~400Gb) of FLAC from the Pony Music Archive corpus show discrepancies compared to ffmpeg. The entire corpus is 900Gb (a mix of MP3 and FLAC), but I don't have enough storage for that locally, so I've only tested the first 400Gb of it.

**Comment by Shnatsel** [comment]
Magnet link to the complete corpus: `magnet:?xt=urn:btih:a28d9ff9d8e1edc220b4511c182345d71739b8c7&dn=Pony%20Music%20Archive%2021.03%20%28Raw%20Quality%29&tr=udp%3A%2F%2Ftracker.opentrackr.org%3A1337%2Fannounce`

**Comment by pdeljanov** [comment]
Those are weird cases.

I tested them against the official FLAC reference decoder and Symphonia's output is a perfect match.

---

I'll add an option to select a reference decoder to `symphonia-check`, but the following code snippet will let you use the official FLAC decoder if interested.

```rust
let mut cmd = Command::new("flac");
let cmd = cmd.arg("--stdout")
             .arg("-d")
             .arg(path)
             .stdout(Stdio::piped())
             .stderr(Stdio::null());
```

**Comment by Shnatsel** [comment]
Oh, did I find a bug in ffmpeg? :joy: 

I'll re-test the entire corpus against the official decoder, then!

**Comment by pdeljanov** [comment]
You could've. Or the reference decoder lol...

**Comment by Shnatsel** [comment]
Yup, no discrepancies compared to the reference decoder :+1:

**Comment by Shnatsel** [comment]
Reporting bugs to ffmpeg is [too much trouble](http://ffmpeg.org/bugreports.html), so I'm just going to leave it at that and close the issue.
