### ISSUE TITLE
symphonia-play: CPAL ring buffer usage is incorrect

### ISSUE THREAD

**Issue by dbeckwith** [pdeljanov/Symphonia#86]
In the CPAL output code for `symphonia-play`, the usage of ring buffer's `write_blocking` is incorrect: https://github.com/pdeljanov/Symphonia/blob/22a6a87b96a6af9ba68b5f9f29ebd10d08a25b17/symphonia-play/src/output.rs#L316-L324

According to the [`rb` docs for `write_blocking`](https://docs.rs/rb/0.3.2/rb/trait.RbProducer.html#tymethod.write_blocking), a `None` return value only means that the given slice had zero length. It has nothing to do with whether the consumer has been dropped, as the code in `symphonia-play` implies. In practice this doesn't matter in this case because the code never calls `write_blocking` with an empty slice, so `None` is never returned, but the usage here is misleading.

Here's an alternative way to write the sample buffer to the ring buffer that I'm using in my project:
```rust
sample_buffer.copy_interleaved_ref(decoded);
let mut samples = sample_buffer.samples();
while let Some(written) = self.ring_buf_producer.write_blocking(samples) {
    samples = &samples[written..];
}
```

**Comment by pdeljanov** [comment]
Thanks @dbeckwith for the correction and the very elegant alternative! Hopefully the previous code didn't throw you for a loop.

**Comment by dbeckwith** [comment]
Not too much, I could relate to the mistake because that's the way most channel-like APIs work. Thank you for this wonderful library!
