### ISSUE TITLE
WAV: Error probing file that can be played by VLC

### ISSUE THREAD

**Issue by dbeckwith** [pdeljanov/Symphonia#87]
I have code that ran `Probe::format` on a file using the default format options and metadata options which resulted in an error `malformed stream: wav: chunk length exceeds parent (list) chunk length`. I'm not sure about the details of this error, but this file can be played fine in VLC. So I guess I have two questions:

1. Would providing non-defaults for the format or metadata options possibly fix this?
2. If not, is there a way that the probe can work around this error since the media seems to be readable by other media players?

**Comment by pdeljanov** [comment]
I don't think there's much that can be done outside of Symphonia to resolve this.

There are two possible scenarios:

1. The file is a WAVE, but encoded weirdly. The issue would be with `WavReader` not handling the special-case as well as other players.
2. The file is not a WAVE, but gets misdetected as one. `Probe` needs improvement.

If you can provide me the file I can look into this. Preferably the whole file, but the first 64kB is usually enough for WAVE.

**Comment by dbeckwith** [comment]
I probably can't share the whole file since it's copyrighted music, but [here is the first 64kB](https://www.dropbox.com/s/v72fighhz7w6t4x/Matt%20Lange%20-%20There%20She%20Goes%20%5Biso001%5D.wav?dl=0).

**Comment by pdeljanov** [comment]
Thanks, that portion of the file was all I needed. This should now be fixed.
