### ISSUE TITLE
Unable to decode mp4 files

### ISSUE THREAD

**Issue by HristoGochevUni** [pdeljanov/Symphonia#89]
Not sure if the support for the decoding of mp4 files is still work in progress but when I try to run the example `basic-interleaved.rs` with any mp4 file I get the following error:

`thread 'main' panicked at 'called 'Result::unwrap()' on an 'Err' value: Unsupported("core (codec):unsupported codec")'`

In my Cargo.toml, I have included the Symphonia crate with the `isomp4` feature.

**Comment by pdeljanov** [comment]
Hi @HristoGochevUni, `isomp4` enables support for the MP4/M4A/MOV container, but not any of the codecs that may be used in the container.

You'll likely also need to enable `aac` for AAC support, `mp3` for MP3 support, or `alac` for ALAC support (if using the Git version). The exact codec required depends on your file.

Hope this helps!

**Comment by HristoGochevUni** [comment]
That worked, thank you! 

Issue can be closed.
