### ISSUE TITLE
Compliance Testing Utility

### ISSUE THREAD

**Issue by pdeljanov** [pdeljanov/Symphonia#9]
Create a new bin crate, sonata-test, that accepts two input files: a WAV reference file, and a test file (any format). The application should decode both files and check if they are sample-for-sample equivalent. Samples that are not the same should have their timestamp printed.

Using the application it should be possible to, for example, compare an FFMPEG decoded MP3 file (converted to WAV) with Sonata's built-in decoder.

FLAC reference files could also be used since the FLAC decoder can verify if it has decoded the file correctly via the the FLAC file's internal MD5 checksum.

**Comment by Shnatsel** [comment]
I understand that in MP3 decoding the output is not expected to match exactly. Rather, the root mean square is used to evaluate MP3 decoder compliance: https://www.underbit.com/resources/mpeg/audio/compliance/

**Comment by pdeljanov** [comment]
Yep, you're correct. Since a MP3 decoder works with real numbers in fixed or floating point there will always be differences between two decoder implementations.

I think a compliance testing utility would find two classes of errors though:

1. General decoding errors (i.e., we just decoded it wrong). These would appear as massive errors.
2. Imprecision in the algorithms implemented. These errors would show up as a larger than allowed RMS error values.

On the other hand, lossless codecs should have a bit-exact output to the reference though. FLAC is very convenient in this regard, it carries a checksum of the entire decoded audio in its header.

**Comment by Shnatsel** [comment]
That's great to see!

If you want to run the tests against something, here are the top 50 largest collections of audio files on archive.org:

https://archive.org/advancedsearch.php?q=mediatype%3A%28audio%29&fl%5B%5D=identifier&sort%5B%5D=item_size+desc&sort%5B%5D=&sort%5B%5D=&rows=50&page=1&callback=callback&save=yes&output=tables

**Comment by pdeljanov** [comment]
Thanks, that's a lot of media!

I have quite a sizable collection myself and unfortunately it didn't take too long find some broken files. :sweat_smile: Once the low hanging fruit is fixed then the more obscure the files to test the better.

**Comment by Shnatsel** [comment]
I have the [MySpace Dragon Hoard](https://archive.org/details/myspace_dragon_hoard_2010) (half a million MP3s) downloaded locally. Let me know if you want me to run any tests on it.

**Comment by pdeljanov** [comment]
I think running those MP3s through `symphonia-check` will be useful at some point, however, at this time I'm aware of atleast one issue with MPEG2 files (a sub-type of MP3) that'll cause a lot of failures. We could start by running them through `symphonia-play --decode-only` to check for panics, errors, etc., then move on to `symphonia-check` once the MPEG2 issue is resolved.

Another area that is missing a lot of testing is Vorbis, and to a lesser extent OGG. I just don't have that many Vorbis files to test. Again, initially we'd just want to test a large collection with `symphonia-play --decode-only`, and then move on to `symphonia-check`. 

In my testing I've found that Symphonia's vorbis decoder is usually within +/-0.00001 of FFMpeg's and triggers a failure. To make a long story short, `symphonia-check` will always fail when testing vorbis files and I need to determine if the precision is just too high or if it's a real bug in the decoder.
