### ISSUE TITLE
Add example how to open and decode music files

### ISSUE THREAD

**Issue by qarmin** [pdeljanov/Symphonia#92]
In my app I use Rodio to open music files.
If there is any error when loading this file, then file is considered as broken
10 lines of this code:
```
                    TypeOfFile::Audio => match fs::File::open(&file_entry.path) {
                        Ok(file) => match rodio::Decoder::new(BufReader::new(file)) {
                            Ok(_) => Some(None), // File is valid
                            Err(e) => {
                                file_entry.error_string = e.to_string();
                                Some(Some(file_entry)) // File is broken
                            }
                        },
                        Err(_inspected) => Some(None), // Failed to open file
                    },
```
The problem is that Rodio require to have installed on os package `libasound-dev` on linux(cpal require this and cannot be disabled, even if unused), which is problematic e.g. on Synology devices.

Looks that Symphony can do exactly same thing without needing to have installed such package, but for now I failed to create similar code, because I can't find any easy method to open files like above(Decoder::new() can be used for flac, mp3, aac etc.)
I only found examples operating on packages instead full files.

**Comment by pdeljanov** [comment]
Hi @qarmin, did you look at the [`examples`](https://github.com/pdeljanov/Symphonia/tree/master/symphonia/examples)? You can also look at [`symphonia-play`](https://github.com/pdeljanov/Symphonia/tree/master/symphonia-play) for a simple  player application.

**Comment by qarmin** [comment]
Hi,
Yes I looked at example, but it is too complicated to use(hundreds lines of code to only open and decode music file) in rodio it is only ~5 lines of code.
Same things is a problem for me with `symphonia-play`

**Comment by pdeljanov** [comment]
Symphonia is a low-level library (like `libavcodec`) so the example is as simple as it gets. The complexity is required to handle many different use cases. I might add a "simple" wrapper in the future, but nothing exists yet.

Perhaps the Rodio developers can help you create a custom Sink to get the samples instead of outputting it to an audio device?
