### ISSUE TITLE
Make format Descriptor available in ProbeResult?

### ISSUE THREAD

**Issue by vatosarmat** [pdeljanov/Symphonia#94]
Hello.

How can I know format of file I'm gonna play?

**Comment by pdeljanov** [comment]
Hi @vatosarmat,

You're right. There is no good way of knowing right now given the current API. I'll see what I can do to resolve this for v0.5.

**Comment by dbeckwith** [comment]
I would also like this feature. Some way to tell from a `dyn FormatReader` what the underlying format is would be great. I'm not sure the format descriptor is totally appropriate since it defines a range of formats that a format reader accepts, not the specific one being used.

**Comment by pdeljanov** [comment]
This is added now in 7e73f3572511f18f270695e649db433f560aa278 in the `dev-0.6` branch.
