### ISSUE TITLE
Vorbis: Mismatch with max delta from 0.05 to 1.95

### ISSUE THREAD

**Issue by Shnatsel** [pdeljanov/Symphonia#97]
Found two new classes of problematic files. One is a random file I found with 0.05 mismatch; AFAIK it's a one-off. The other is from Doom Eternal soundtrack with files extracted from the game, and I have over 100 such files with mismatches over 1. I've included one as a sample.

Files: [problematic-ogg-new.tar.gz](https://github.com/pdeljanov/Symphonia/files/7917576/problematic-ogg-new.tar.gz)

Tested on commit 3dc2e7b131a5f3c876188ea7957876ff05116c8a

**Comment by Shnatsel** [comment]
Everything else in my 200Gb collection is showing a delta of 0.0000007 or less.

**Comment by pdeljanov** [comment]
Thanks, that's encouraging!

All the Doom files should be fixed with that last commit. That one had 3 audio channels and they weren't being mapped correctly in the output buffer.

The other file may take a bit a time.

**Comment by pdeljanov** [comment]
Actually, I ran `symphonia-check` with an `oggdec` (libvorbis reference decoder) backend, and it gives an absolute maximum error of `0.00001535` (likely differences in their FFT implementation) vs. `ffmpeg` which gives `0.05350513`. 

Not sure if that one-off is really an issue... :thinking:

**Comment by Shnatsel** [comment]
Yeah, I suppose a difference of 0.00001 is more than good enough. Thanks!
